import type { Metadata } from "next";
import "./globals.css";
import { SignalRProvider } from "@/app/providers";
import { rubik } from "@/app/fonts";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${rubik.className} antialiased w-dvw h-dvh p-6 flex bg-stone-100`}
            >
                <SignalRProvider>{children}</SignalRProvider>
            </body>
        </html>
    );
}
